"""THE 105 canonical event contracts, their validation, and the upcaster (P5 U5.3).

WHAT `event_envelope` DELIBERATELY LEFT UNDONE, AND THIS MODULE FINISHES

`event_envelope.py` says it in its own words: *"It is not the 105 event contracts. There is no name
whitelist here, no per-event payload schema, and no upcaster: those are U5.3's."* So an envelope
today can carry `event_name="Vibes"` with an empty payload and be perfectly well-formed. It is
SHAPED like a canonical event and it is not one.

This module is what makes `event_name` mean something:

    IS IT A CANONICAL FACT?    the name is one of the 118 contracts, or it is refused.
    DID THAT TRANSITION EMIT IT?   `producer_transition_id` belongs to the contract, or it is refused.
    IS THE BODY THE DECLARED BODY?  required fields present, enums honoured, fixed values fixed.
    CAN THIS BINARY READ IT?   the version is supported, or it is refused — never guessed at.
    IS THE DECISION REPRODUCIBLE?   a CONSEQUENTIAL event pins its decision context (§5, ER-13).
    MAY THIS ACTOR SAY THIS?   ER-9/10/11/12 — a model cannot state a fact, a machine cannot
                               release a brake, and nothing automated may assert OWNER_ASSERTED.

THE CONTRACTS ARE DERIVED, NOT TRANSCRIBED

`event_contracts_data.json` is generated by `scripts/generate_event_contracts.py` from
`events/registry.md` §3/§5/§8 and the F1–F14 family files, and a guard re-derives it on every suite
run. Nothing in this file names an event. The registry stays "the sole canonical list of event
names and versions" (§6) and this module is a reader of it — which is the only way two authorities
for one list never come into existence.

### 118 CONTRACTS, OF WHICH 105 ARE "THE 105". F1–F13 are the machine-emitted corpus the registry
counts and the plan calls the 105 event contracts. F14 is the audit/security surface — thirteen
real contracts, emitted by detectors and by the inbox rather than by a producer transition, which
is why they carry no producer set and are not producer-checked.

WHY VALIDATION HAS TWO MODES, AND WHY THAT IS NOT A LOOPHOLE

§6 is explicit and asymmetric: *"a `vN+1` producer + a `vN` consumer ⇒ additive fields are
ignored"*. A consumer that refused an unrecognised payload field would make every additive schema
change a coordinated outage — the exact opposite of what "additive within a version" is for.

    PRODUCER mode   an undeclared payload field is a REFUSAL. Our own emitters must not invent
                    fields; a typo is caught in the commit that introduces it, not in an audit.
    CONSUMER mode   an undeclared payload field is IGNORED, per §6. Everything else — required
                    fields, enums, fixed values, versions, actor authority — is checked identically.

Neither mode is lenient about whether the event is canonical. The difference is exactly one rule,
and it is the rule §6 writes down.

THE UPCASTER, AND AN HONEST ACCOUNT OF WHAT IT HAS TO DO TODAY

§6: a breaking change ships a new version plus a registered `vN→vN+1` upcaster, deterministic,
applied ON READ; historical events are never rewritten (S8); no historical event may become
unreadable because current code changed (M-25).

### EVERY CONTRACT IN THE CANONICAL CORPUS IS AT `v1` TODAY. That is a fact about the
specification, not a gap in this module, and it has a consequence worth stating plainly rather than
dressing up: **the corpus registers zero upcasters, because nothing has evolved yet.** What is
built and exercised is the machinery that will carry the first evolution — registration, chaining,
determinism, and the three refusals below — proven in the suite against a synthetic contract set
rather than against a v2 of a canonical event that founder/architect authority has not minted.
Inventing such a v2 here to make a test look impressive would be amending a protected
specification, which is a defect wearing a green tick.

    version == current    identity. No upcaster runs, the document is returned unchanged.
    version <  current    chain vN→vN+1→…→current. A MISSING link is `MissingUpcaster` — never a
                          silent pass-through, because a v1 document read as a v3 is a fact with
                          three years of assumptions the reader does not know it is making.
    version >  current    `UnsupportedFutureVersion`. This binary cannot know what a later schema
                          means. §6's mixed-version rule is that a breaking change is gated on a
                          coordinated rollout, so a future version arriving here is a deployment
                          error and it fails closed.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from .event_envelope import EnvelopeError, EventEnvelope

# ### THE CONTRACT DATA IS JSON, AND THAT IS A SAFETY PROPERTY RATHER THAN A FILE-FORMAT PREFERENCE.
# It was a `.py` module holding one tuple literal, and an independent review defeated the AST guard
# that proved it inert: a module-level `if` assembles a policy decision at import time with no
# function, class or call anywhere in it. JSON cannot execute, so nothing has to prove that it does
# not.
#
# It also keeps the typed gate vocabulary out of every Python module. One contract's payload fixes
# a gate-decision value (PL-7a's, ADR-010's ladder), and the Phase-0 confinement guard scans `*.py`
# for exactly those tokens — so holding the corpus as data means that guard keeps its original
# kernel-only rule and needs no amendment. This module never names a gate value either; it compares
# whatever the contract carries. The safest change to a safety guard is the one you do not make.
_DATA_PATH = Path(__file__).with_name("event_contracts_data.json")

# --------------------------------------------------------------------------------- the exceptions

# ### EVERY CONTRACT FAILURE IS AN `EnvelopeError`. `event_inbox` refuses an event it cannot
# construct by catching `EnvelopeError` and recording `REJECTED_MALFORMED`. A contract violation is
# the same class of thing — this is not a canonical event — so it travels the same path and lands in
# the same durable outcome. A separate exception hierarchy would have needed a second refusal branch
# in the inbox, and the branch that is written twice is the branch that diverges.


class ContractError(EnvelopeError):
    """This is not a canonical event. Fail closed."""


class UnknownEventName(ContractError):
    """The name is not one of the canonical contracts (`events/registry.md` §3).

    Refused rather than passed through: an unknown name is either a typo, a binary older than the
    fact it is reading, or something inventing operational history. None of the three may proceed.
    """


class ProducerTransitionMismatch(ContractError):
    """The contract is canonical but the transition claiming to have emitted it does not own it.

    §1 calls `producer_transition_id` "the mechanical link to the state machine". An event asserting
    `BrakeReleased` from `WI-1` is a broken link, and a broken link is how a fact gets attributed to
    a transition that could not have produced it.
    """


class AggregateTypeMismatch(ContractError):
    """The event is on the wrong kind of aggregate for its family."""


class UnsupportedFutureVersion(ContractError):
    """The event is at a version later than this binary's contract. It is NOT guessed at (§6)."""


class UnsupportedEventVersion(ContractError):
    """A producer tried to emit a version that is not its contract's current one.

    Reading an old version forward is the CONSUMER's job and it has an upcaster for it. Writing one
    fresh is nobody's: it produces a fact whose body and whose stamped version disagree.
    """


class MissingUpcaster(ContractError):
    """An older supported version arrived and no registered upcaster can bring it forward (M-25)."""


class PayloadContractViolation(ContractError):
    """The body is not the body the contract declares."""


class ConsequentialPinsMissing(ContractError):
    """A consequential event did not pin the context needed to reproduce its decision (§5, ER-13)."""


class ActorAuthorityViolation(ContractError):
    """ER-9/10/11/12 — this actor class may not state this fact."""


# ------------------------------------------------------------------------------------ the contract

@dataclass(frozen=True)
class FieldSpec:
    """One declared payload field, exactly as its family file writes it."""

    name: str
    required: bool
    listed: bool                      # declared `name[]` — the value must be a list
    enum: tuple[str, ...] | None
    fixed: str | None


@dataclass(frozen=True)
class OneOfGroup:
    """`rule_id \\| decision_ref`(R, exactly one) — a choice, not two optional fields."""

    members: tuple[str, ...]
    required: bool


@dataclass(frozen=True)
class CanonicalContract:
    """One canonical event contract."""

    name: str
    family: str
    source: str                       # the family file that declares it
    current_version: int
    producers: tuple[str, ...]        # transition ids; empty for F14 (detectors, the inbox)
    coordination: bool                # ‡ — one contract, several structurally-identical producers
    aggregate_type: str | None        # the family default; None where the family declines to fix it
    emitted_corpus: bool              # F1-F13 — "the 105"
    consequential: bool               # §5
    consequential_conditional: bool   # §5 membership carries a qualifier
    strict_order: bool                # §8
    human_only: bool                  # the family file declares `actor_type=human` ONLY
    fields: tuple[FieldSpec, ...]
    one_of: tuple[OneOfGroup, ...]

    @property
    def supported_versions(self) -> tuple[int, ...]:
        return tuple(range(1, self.current_version + 1))

    @property
    def declared_field_names(self) -> frozenset[str]:
        return frozenset(
            [f.name for f in self.fields] + [m for g in self.one_of for m in g.members]
        )


def _build() -> dict[str, CanonicalContract]:
    # Fail-closed either way — without contracts nothing can emit or consume — but say WHY, because
    # a bare KeyError at import cascades into `event_outbox` and `event_inbox` and reads like a
    # packaging fault rather than a stale or missing artifact.
    try:
        document = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
        rows = document["contracts"]
    except FileNotFoundError as exc:
        raise ContractError(
            f"the canonical contract data is missing at {_DATA_PATH}. It is generated: run "
            f"`python3 scripts/generate_event_contracts.py`."
        ) from exc
    except (ValueError, KeyError, TypeError) as exc:
        raise ContractError(
            f"the canonical contract data at {_DATA_PATH} is not readable as a contract set "
            f"({exc}). It is generated from docs/specifications/events/ — regenerate it rather "
            f"than editing it."
        ) from exc
    contracts: dict[str, CanonicalContract] = {}
    for row in rows:
        contracts[row["name"]] = CanonicalContract(
            name=row["name"], family=row["family"], source=row["source"],
            current_version=row["current_version"], producers=tuple(row["producers"]),
            coordination=row["coordination"], aggregate_type=row["aggregate_type"],
            emitted_corpus=row["emitted_corpus"], consequential=row["consequential"],
            consequential_conditional=row["consequential_conditional"],
            strict_order=row["strict_order"], human_only=row["human_only"],
            fields=tuple(
                FieldSpec(
                    name=f["name"], required=f["required"], listed=f["listed"],
                    enum=tuple(f["enum"]) if f["enum"] else None, fixed=f["fixed"],
                )
                for f in row["fields"]
            ),
            one_of=tuple(
                OneOfGroup(tuple(g["members"]), g["required"]) for g in row["one_of"]
            ),
        )
    return contracts


CONTRACTS: Mapping[str, CanonicalContract] = _build()

# The registry's own count, computed rather than asserted. `EMITTED_CORPUS` is "the 105".
EMITTED_CORPUS: frozenset[str] = frozenset(n for n, c in CONTRACTS.items() if c.emitted_corpus)
CONSEQUENTIAL_EVENTS: frozenset[str] = frozenset(n for n, c in CONTRACTS.items() if c.consequential)


def contract_for(event_name: str) -> CanonicalContract:
    """The contract, or a refusal. There is no "unknown but probably fine"."""
    contract = CONTRACTS.get(event_name)
    if contract is None:
        raise UnknownEventName(
            f"{event_name!r} is not a canonical event contract. `events/registry.md` §3 is the sole "
            f"canonical list of event names ({len(CONTRACTS)} contracts: {len(EMITTED_CORPUS)} "
            f"machine-emitted F1-F13, {len(CONTRACTS) - len(EMITTED_CORPUS)} audit/security F14). "
            f"An unknown name is refused, never recorded as operational history."
        )
    return contract


# ------------------------------------------------------------------------------- actor authority

# ### DERIVED FROM THE FAMILY FILES, NOT LISTED HERE. An earlier version of this line was a
# hand-written literal `{"PolicyActivated", "BrakeReleased", "BrakeNarrowed"}` that mechanised
# ER-11/ER-12 verbatim and stopped there — so `ApprovalGranted` (AP-2), the single most
# authority-broadening event in the corpus and the human consent that binds Material Facts, and
# `RuleActivated` (RU-5) both accepted `actor_type=system`. Their family rows say
# "`actor_type=human` ONLY" in as many words. The set now comes from those rows (see
# `parse_human_only` in the generator, which distinguishes an UNCONDITIONAL declaration from
# `ClaimConfirmed`'s conditional one), and a new contract that declares the constraint is covered
# the day it is minted rather than the day someone remembers to edit this file.
HUMAN_ONLY_EVENTS: frozenset[str] = frozenset(n for n, c in CONTRACTS.items() if c.human_only)

# ER-9: `actor_type=model` may produce only CLAIM/PROPOSAL events. The decidable reading of "claim
# or proposal" over the canonical corpus: the F6 Identity-Binding-Claim family, plus every contract
# whose name is a proposal (`ClaimProposed`, `PolicyProposed`, `RuleProposed`).
#
# ### `ClaimConfirmed` IS SUBTRACTED, AND THE SUBTRACTION IS THE POINT. Blanket F6 membership reads
# the family LABEL rather than its contents. IB-2's own row says it "proves a binding is canonical
# via a **deterministic** method or an **authenticated human**", and its family notes say a
# `MODEL_INFERRED` claim lands at `ClaimAmbiguous` — "never `CONFIRMED`, at any confidence (GR-8)".
# It is also CONSEQUENTIAL under §5. So it is the one F6 contract that states a FACT, and ER-9's
# "a model-generated claim stays a claim, never a fact" excludes it by its own words.
_MODEL_FORBIDDEN_CLAIMS: frozenset[str] = frozenset({"ClaimConfirmed"})

MODEL_PERMITTED_EVENTS: frozenset[str] = frozenset(
    n for n, c in CONTRACTS.items()
    if (c.family == "F6" or n.endswith("Proposed")) and n not in _MODEL_FORBIDDEN_CLAIMS
)

# ER-10: an `OWNER_ASSERTED`-provenance event cannot be produced by a machine actor. The provenance
# travels in the payload, so this is decidable per event rather than per contract.
OWNER_ASSERTED = "OWNER_ASSERTED"

_AUTOMATED_ACTORS = frozenset({"system", "detector", "model"})


def _token(value: object) -> str:
    """One payload value as the token the CONTRACT sees.

    ### THE TWO READINGS MUST AGREE, AND THEY DID NOT. `_check_payload` resolves an `Enum` member
    by `.name` (§1 mandates "enums by name" for canonical serialization), so an
    `Enum.OWNER_ASSERTED` was accepted INTO the declared enum — while the ER-10 check compared the
    same object to a `str` and concluded it was not OWNER_ASSERTED. The payload validator agreed the
    value was OWNER_ASSERTED and the authority validator did not, in one call. One resolver now
    serves both.
    """
    return value.name if isinstance(value, Enum) else str(value)


def _asserts_owner_provenance(envelope: EventEnvelope) -> bool:
    """Does this event assert `OWNER_ASSERTED` provenance in its PAYLOAD or its `provenance_refs`?

    ### THE REACH IS BOUNDED, AND THE BOUNDS ARE STATED RATHER THAN IMPLIED. It scans those two
    surfaces to a depth of 8. It does NOT scan `metadata`, which §1 defines as "non-authoritative
    annotations (never gates anything)" — a provenance claim there gates nothing by definition —
    nor `evidence_refs`/`observation_refs`, which carry content-addressed references rather than
    provenance. A lineage nested more than 8 deep is also out of reach. An earlier version of this
    docstring said "ANYWHERE it could be read from", which was not true of the code.

    Three evasions closed at once, each of which passed validation with `actor_type=system`:

      * a nested payload structure, because the old check was a single scalar `payload.get`;
      * an `Enum` member rather than a string (see `_token`);
      * ### `provenance_refs` AT THE ENVELOPE LEVEL — which is not an edge case but the field §1
        DEFINES as "the `provenance_class` + lineage of any claim/value carried". The canonical home
        for provenance was the one place the check never looked.

    Structural rather than a substring scan, so the word appearing inside ordinary prose is not
    mistaken for a provenance assertion.
    """
    def walk(value: object, depth: int) -> bool:
        if depth > 8:
            return False
        if isinstance(value, Mapping):
            for key, item in value.items():
                if str(key) == "provenance_class" and _token(item) == OWNER_ASSERTED:
                    return True
                if walk(item, depth + 1):
                    return True
            return False
        if isinstance(value, (list, tuple)):
            return any(walk(item, depth + 1) for item in value)
        return False

    return walk(envelope.payload, 0) or walk(envelope.provenance_refs or {}, 0)


def _check_actor_authority(envelope: EventEnvelope, contract: CanonicalContract) -> None:
    actor = envelope.actor_type

    if contract.name in HUMAN_ONLY_EVENTS and actor != "human":
        raise ActorAuthorityViolation(
            f"{contract.name} requires `actor_type=human` (ER-11/ER-12): it broadens authority, and "
            f"automation may narrow authority but never broaden it. This event carries "
            f"actor_type={actor!r}. The canonical response to an automated attempt is to record "
            f"`UnauthorizedPolicyActivationAttempted` or `UnauthorizedBrakeReleaseAttempted` (F14), "
            f"not to accept the event."
        )

    if actor == "model" and contract.name not in MODEL_PERMITTED_EVENTS:
        raise ActorAuthorityViolation(
            f"actor_type=model may only produce claim/proposal events (ER-9), and {contract.name} "
            f"is neither. A model-generated fact stays a claim; it never becomes truth by being "
            f"written to an event stream."
        )

    if actor in _AUTOMATED_ACTORS and _asserts_owner_provenance(envelope):
        raise ActorAuthorityViolation(
            f"{contract.name} carries provenance_class={OWNER_ASSERTED} with actor_type={actor!r}. "
            f"An OWNER_ASSERTED fact is one a human asserted; a machine actor cannot produce one "
            f"(ER-10), and letting it would launder an inference into an owner's word."
        )


# --------------------------------------------------------------------------- consequential pinning

# §5: each consequential event "MUST pin the SD-3 `entity_versions` set, the
# `material_facts_fingerprint` where an amount is involved, `policy_version`, and `brake_version`".
#
# ### THE FINGERPRINT IS DELIBERATELY NOT REQUIRED HERE, AND THAT IS NOT AN OVERSIGHT. §5 qualifies
# it with "where an amount is involved", and whether an amount is involved is a property of the
# decision, not of the envelope — this module cannot decide it without guessing. Where the
# specification DOES fix it, the family file declares `material_facts_fingerprint`(R) in the payload
# (`CheckpointPassed`, `EffectGranted`, `ApprovalBound`), and ordinary field validation enforces it
# exactly. Requiring it unconditionally here would refuse legitimate events on a rule the
# specification did not write.
_CONSEQUENTIAL_PINS = ("entity_versions", "policy_version", "brake_version")


def _check_consequential_pins(envelope: EventEnvelope, contract: CanonicalContract) -> None:
    if not contract.consequential:
        return
    if contract.consequential_conditional:
        # ### §5 QUALIFIES THIS MEMBERSHIP, AND THE QUALIFIER IS NOT DECIDABLE HERE.
        # `ClaimConfirmed`(when it backs a money action) — whether a binding backs a money action is
        # a property of the DECISION, not of the envelope. Enforcing the pins unconditionally
        # refused every ordinary deterministic (LINKER_INFERRED / RECONCILED) confirmation on a rule
        # §5 does not apply to them. Same reasoning as `material_facts_fingerprint`'s "where an
        # amount is involved" (see `_CONSEQUENTIAL_PINS` above): where the specification qualifies a
        # requirement with something this layer cannot evaluate, refusing anyway invents a rule.
        return
    # Blank-safe: a pin that is `""` or `"   "` reproduces exactly as much decision context as an
    # absent one, and ER-13 is about being able to reproduce the decision, not about the field
    # being syntactically present.
    def _unpinned(value: object) -> bool:
        if value is None:
            return True
        if isinstance(value, str):
            return not value.strip()
        if isinstance(value, (Mapping, list, tuple, set)):
            return not value
        return False

    missing = [p for p in _CONSEQUENTIAL_PINS if _unpinned(getattr(envelope, p, None))]
    if missing:
        raise ConsequentialPinsMissing(
            f"{contract.name} is a CONSEQUENTIAL event (`events/registry.md` §5) and did not pin "
            f"{missing}. ER-13: a consequential event carries enough refs to reproduce its decision "
            f"context AT THAT TIME. Without the pins the audit can say what was decided but never "
            f"why it was allowed, which is the difference between a log and evidence."
        )


# -------------------------------------------------------------------------------- payload checking

class ValidationMode(str, Enum):
    """See the module docstring: the two modes differ by exactly one rule, and §6 writes that rule."""

    PRODUCER = "PRODUCER"     # our own emitter — an undeclared field is a refusal
    CONSUMER = "CONSUMER"     # §6 — additive fields from a newer producer are ignored


def _describe(value: object) -> str:
    return f"{type(value).__name__}"


def _check_payload(envelope: EventEnvelope, contract: CanonicalContract,
                   mode: ValidationMode) -> None:
    payload = envelope.payload

    for spec in contract.fields:
        present = spec.name in payload
        if not present:
            if spec.required:
                raise PayloadContractViolation(
                    f"{contract.name} payload is missing required field {spec.name!r}. Its contract "
                    f"is declared in `docs/specifications/events/{contract.source}`; an event that "
                    f"omits a declared fact is an event that cannot support the transition it "
                    f"claims to record."
                )
            continue

        value = payload[spec.name]

        # `null ≠ absent` (§1). A required field present as null is a stated "we looked and there
        # is nothing", which for a REQUIRED field is a contradiction rather than a value.
        if spec.required and value is None:
            raise PayloadContractViolation(
                f"{contract.name} payload field {spec.name!r} is required and is present as null. "
                f"In ev_v1 `null` means 'we looked and there is no value', which a required fact "
                f"cannot be. Omit the field or supply it — those are different facts (§1)."
            )

        if spec.listed and value is not None and not isinstance(value, (list, tuple)):
            raise PayloadContractViolation(
                f"{contract.name} payload field {spec.name!r} is declared `{spec.name}[]` and must "
                f"be a list; got {_describe(value)}."
            )
        # ### THE CONVERSE — DELIBERATELY NARROW, AND THE NARROWNESS IS THE CORRECTION.
        #
        # The real defect was `ClaimRefused.cause = ["already_claimed", "expired", "revoked"]`
        # passing: the enum check below ITERATES a collection and approves each member
        # individually, so three incompatible causes were each individually legal.
        #
        # The first fix for it refused ANY collection in ANY field not written `name[]`, and that
        # was the same mistake as reading a derivation formula as a fixed value — a rule the
        # specification does not write, refusing values it explicitly requires. ### IT MADE 14
        # CANONICAL CONTRACTS UNSATISFIABLE, including `CheckpointPassed`, whose `entity_versions`
        # the family file declares `(R, SD-3 set)` and §1 defines as a SET of entity versions. The
        # corpus marks a collection with the ANNOTATION as often as with `[]` —
        # `caps_evaluated`(R — each cap id with its limit and the observed value), `scope`
        # (tenant + action_class), plural `evidence_refs`, `refs`, `drift_diff` — and none of them
        # carry the marker.
        #
        # So the refusal is confined to exactly where the defect lived: a field CONSTRAINED to one
        # of a declared set, or fixed to one value. Those cannot be collections by their own
        # definition, and every one of the 14 legitimate structured fields has neither constraint.
        # A general "a scalar may not be structured" rule is a specification decision, not a
        # validator's to invent.
        if ((spec.enum is not None or spec.fixed is not None)
                and not spec.listed and isinstance(value, (list, tuple, Mapping))):
            raise PayloadContractViolation(
                f"{contract.name} payload field {spec.name!r} is constrained to a single declared "
                f"value and carries {_describe(value)}. A collection here is several answers to a "
                f"question that has one — and the enum check would otherwise approve each member "
                f"of it separately."
            )

        if spec.fixed is not None and value is not None:
            # `frozen=true` is declared as the string `true` in markdown; the canonical payload may
            # legitimately carry the JSON boolean. Compare on the rendered token, so the contract is
            # satisfied by the VALUE the specification names rather than by its Python spelling.
            # `_token`, not `str()` — the enum check resolves an `Enum` by `.name`, so a bare
            # `str()` here rendered `Prov.OWNER_ASSERTED` and refused a value the enum path had just
            # accepted. That is the very asymmetry `_token` exists to abolish, surviving in the one
            # branch that did not call it.
            rendered = ("true" if value is True else "false" if value is False else _token(value))
            if rendered != spec.fixed:
                raise PayloadContractViolation(
                    f"{contract.name} payload field {spec.name!r} is fixed to {spec.fixed!r} by its "
                    f"contract and carries {value!r}. A fixed value is the fact the event exists to "
                    f"record; an event asserting a different one is asserting something else."
                )

        if spec.enum is not None and value is not None:
            candidates = value if isinstance(value, (list, tuple)) else [value]
            for item in candidates:
                token = item.name if isinstance(item, Enum) else str(item)
                if token not in spec.enum:
                    raise PayloadContractViolation(
                        f"{contract.name} payload field {spec.name!r} carries {token!r}, which its "
                        f"contract does not permit. Declared: {list(spec.enum)}."
                    )

    for group in contract.one_of:
        # ### TWO DIFFERENT QUESTIONS, SO TWO DIFFERENT TESTS — AND CONFLATING THEM ADMITTED AN
        # EMPTY ANSWER. Stating `rule_id: null` is an ANSWER ("we looked and there is no rule"), so
        # for "did you answer twice?" it counts: `{rule_id: null, decision_ref: "d-1"}` is two
        # answers to a one-of and is refused. But it is not an ANSWER WITH A VALUE, so for "did you
        # answer at all?" it does not count — a key-membership test alone accepted a
        # `ConflictResolved` carrying no resolution reference whatsoever, which is the same
        # `null ≠ absent` rule the required-field check applies 60 lines above.
        answered = [m for m in group.members if m in payload]
        present = [m for m in answered if payload[m] is not None]
        if len(answered) > 1:
            raise PayloadContractViolation(
                f"{contract.name} declares `{' | '.join(group.members)}` as EXACTLY ONE and carries "
                f"{answered}. Two answers to a one-of is not extra information; it is an "
                f"unresolvable fact."
            )
        if group.required and not present:
            raise PayloadContractViolation(
                f"{contract.name} declares `{' | '.join(group.members)}` as exactly one, required, "
                f"and carries no value for either"
                + (f" ({answered} present but null — `null` states an absence, and a required "
                   f"choice cannot be answered with one)." if answered else ".")
            )

    if mode is ValidationMode.PRODUCER:
        declared = contract.declared_field_names
        undeclared = sorted(k for k in payload if k not in declared)
        if undeclared:
            raise PayloadContractViolation(
                f"{contract.name} payload carries undeclared field(s) {undeclared}. Its contract is "
                f"in `docs/specifications/events/{contract.source}`; declared: "
                f"{sorted(declared)}. ### A PRODUCER MAY NOT INVENT A FIELD — an additive change is "
                f"a specification edit followed by a regeneration, not a key added at a call site. "
                f"(A CONSUMER reading this same event IGNORES unknown fields, per §6's "
                f"mixed-version rule; this refusal is the producer-side half.)"
            )


# ------------------------------------------------------------------------------------ the upcaster

# An upcaster takes a payload document at version N and returns the document at version N+1.
# Deterministic by contract: given the same input it must return the same output, because a
# full-history rebuild runs it again every single time (M-25).
Upcaster = Callable[[Mapping[str, Any]], Mapping[str, Any]]


class UpcasterRegistry:
    """The registered `vN→vN+1` upcasters, and the chain that applies them ON READ (§6).

    Keyed `(event_name, from_version)`. Registration refuses to overwrite: two upcasters for one
    step would make the reconstructed history depend on import order, and a rebuild whose result
    depends on import order is not a rebuild.
    """

    def __init__(self, contracts: Mapping[str, CanonicalContract] | None = None) -> None:
        self._upcasters: dict[tuple[str, int], Upcaster] = {}
        # The contract set this registry resolves names against. Injectable for ONE reason, stated
        # plainly: every canonical contract is at v1, so the canonical corpus cannot exercise a real
        # v1→v2→v3 chain, and the alternative — minting a fake v2 of a real event — would amend a
        # protected specification to make a test look good. A synthetic contract set lets the
        # CHAINING be proven for what it is (mechanism), while the canonical corpus proves what IT
        # is (identity, and three refusals). Neither pretends to be the other.
        self._contracts = contracts

    def _contract_for(self, event_name: str) -> CanonicalContract:
        if self._contracts is None:
            return contract_for(event_name)
        contract = self._contracts.get(event_name)
        if contract is None:
            raise UnknownEventName(
                f"{event_name!r} is not a contract in this registry's contract set"
            )
        return contract

    def register(self, event_name: str, from_version: int, upcaster: Upcaster) -> None:
        contract = self._contract_for(event_name)
        if from_version < 1:
            raise ContractError(f"upcaster from_version must be >= 1, got {from_version}")
        if from_version >= contract.current_version:
            raise ContractError(
                f"an upcaster for {event_name} v{from_version}→v{from_version + 1} would produce a "
                f"version later than the contract's current v{contract.current_version}. Bump the "
                f"contract in the specification first — the upcaster follows the version, it does "
                f"not create it."
            )
        key = (event_name, from_version)
        if key in self._upcasters:
            raise ContractError(
                f"an upcaster for {event_name} v{from_version}→v{from_version + 1} is already "
                f"registered. Two upcasters for one step make a rebuild depend on import order."
            )
        if not callable(upcaster):
            raise ContractError("an upcaster must be callable")
        self._upcasters[key] = upcaster

    def registered_steps(self) -> tuple[tuple[str, int], ...]:
        return tuple(sorted(self._upcasters))

    def upcast_payload(self, event_name: str, version: int,
                       payload: Mapping[str, Any]) -> Mapping[str, Any]:
        """Bring one payload forward to its contract's current version. Identity when already there."""
        contract = self._contract_for(event_name)
        if version < 1:
            raise ContractError(f"{event_name} carries event_version {version}; §1 requires >= 1")
        if version > contract.current_version:
            raise UnsupportedFutureVersion(
                f"{event_name} arrived at v{version} but this binary's contract is "
                f"v{contract.current_version}. A later schema is not guessed at: §6 gates a "
                f"breaking change on a coordinated rollout, so this is a deployment error and it "
                f"fails closed rather than reading fields it does not understand."
            )
        current = dict(payload)
        for step in range(version, contract.current_version):
            upcaster = self._upcasters.get((event_name, step))
            if upcaster is None:
                raise MissingUpcaster(
                    f"{event_name} is at v{step} and the contract is at "
                    f"v{contract.current_version}, but no v{step}→v{step + 1} upcaster is "
                    f"registered. M-25: no historical event may become unreadable because current "
                    f"code changed. Reading it as-is would silently reinterpret an old fact under "
                    f"new assumptions."
                )
            produced = upcaster(current)
            if not isinstance(produced, Mapping):
                raise ContractError(
                    f"the {event_name} v{step}→v{step + 1} upcaster returned "
                    f"{_describe(produced)}; an upcaster returns the payload document"
                )
            current = dict(produced)
        return current

    def upcast(self, envelope: EventEnvelope) -> EventEnvelope:
        """The envelope, at its contract's current version, with its payload brought forward.

        Returns the SAME object when nothing changed, so the common path allocates nothing and an
        identity upcast cannot accidentally alter a digest.
        """
        contract = self._contract_for(envelope.event_name)
        if envelope.event_version == contract.current_version:
            # Still range-checked above by contract_for; an equal version needs no transformation.
            return envelope
        payload = self.upcast_payload(envelope.event_name, envelope.event_version, envelope.payload)
        document = envelope.as_document()
        document["event_version"] = contract.current_version
        document["payload"] = dict(payload)
        return EventEnvelope.from_document(document)


# The process-wide registry. Empty today, and the module docstring says why in full: every canonical
# contract is at v1, so there is nothing to upcast FROM. It is a real registry, not a placeholder —
# `upcast` already refuses future versions and missing links against it.
UPCASTERS = UpcasterRegistry()


# ------------------------------------------------------------------------------ the public checks

def validate(envelope: EventEnvelope, *, mode: ValidationMode = ValidationMode.PRODUCER) -> None:
    """Is this a canonical event? Raises a `ContractError` subclass if not; returns None if so.

    Order matters and is deliberate: identity first (is this even a real contract), then
    attribution, then version, then body, then authority. Each answer makes the next question
    meaningful, and the first failure is the most informative one.
    """
    contract = contract_for(envelope.event_name)

    if contract.producers and envelope.producer_transition_id not in contract.producers:
        raise ProducerTransitionMismatch(
            f"{contract.name} is emitted by {list(contract.producers)}, and this event names "
            f"{envelope.producer_transition_id!r}. §1 calls `producer_transition_id` the mechanical "
            f"link to the state machine"
            + (" (this is a ‡coordination contract, so it has several structurally-identical "
               "producers — but only those)." if contract.coordination else ".")
        )

    if contract.aggregate_type is not None and envelope.aggregate_type != contract.aggregate_type:
        raise AggregateTypeMismatch(
            f"{contract.name} belongs to aggregate_type {contract.aggregate_type!r} (its family "
            f"default in `docs/specifications/events/{contract.source}`) and this event is on "
            f"{envelope.aggregate_type!r}. The ordering key is "
            f"(tenant_id, aggregate_id, aggregate_version) — an event on the wrong aggregate orders "
            f"against the wrong history."
        )

    if envelope.event_version > contract.current_version:
        raise UnsupportedFutureVersion(
            f"{contract.name} arrived at v{envelope.event_version}; this binary's contract is "
            f"v{contract.current_version}. Refused rather than read (§6)."
        )
    if mode is ValidationMode.PRODUCER and envelope.event_version != contract.current_version:
        # ### A PRODUCER EMITS THE CURRENT VERSION OR NOTHING. Only the future case was checked, so
        # on the day a contract goes to v2 an emitter could stamp `event_version=1` on a body
        # validated against the v2 field set and commit it. A consumer would then either fail on a
        # missing upcaster or run a v1→v2 upcaster over a body that is already v2-shaped —
        # corrupting the fact rather than refusing it. Reading an old version is the CONSUMER's job,
        # and it has an upcaster for it; writing one is nobody's.
        raise UnsupportedEventVersion(
            f"{contract.name} is being EMITTED at v{envelope.event_version} while its contract is "
            f"v{contract.current_version}. A producer emits the current version; historical "
            f"versions are read forward by the upcaster (§6), never written fresh."
        )

    _check_payload(envelope, contract, mode)
    _check_consequential_pins(envelope, contract)
    _check_actor_authority(envelope, contract)


def is_canonical(event_name: str) -> bool:
    """Membership, without raising — for reporting surfaces, never as a gate before an effect."""
    return event_name in CONTRACTS


def read(envelope: EventEnvelope, *, upcasters: UpcasterRegistry | None = None) -> EventEnvelope:
    """The consumer's read path: upcast to the current version, then validate in CONSUMER mode.

    This is the whole of §6's "applied on read", as one call. A consumer never sees a historical
    representation: by the time a handler is reached, the event is at the contract's current
    version or it was refused.
    """
    registry = upcasters if upcasters is not None else UPCASTERS
    current = registry.upcast(envelope)
    validate(current, mode=ValidationMode.CONSUMER)
    return current
